### ISSUE TITLE
Some Pokemon Ultra Moon Codes not working

### ISSUE THREAD

**Issue by Questioner67** [JourneyOver/CTRPF-AR-CHEAT-CODES#51] opened 2018-10-05 20:41 UTC
## Checklist:

- [x] Broken Cheat
- [ ] Multi-Region
- [ ] Versioning
- [ ] Wrong Game
- [ ] Other

## Extra Information (only need to fill in if issuing for Broken Cheats)
**Type of 3DS:** [e.g. New 3DS, Old 3DS, 2DS]

**3DS Firmware Version:** [e.g. 11.6.0-39E]

**Method Used:** [e.g. LUMAS3DS 9.0 Plugin Loader, BOOTNTR]

**Game Version:** [e.g. 1.0, 1.1]

**Language & Region:** [e.g. English & USA]

**Comment by Questioner67** [comment] 2018-10-05 21:19
21 94 57 JourneyOver/CTRPF-AR-CHEAT-CODES
 
CTRPF-AR-CHEAT-CODES/Cheats/Pokémon Ultra Moon (GLO)/00040000001B5100.txt
50e93c3  on Apr 26
@JourneyOver JourneyOver DB Updates
@JourneyOver @M1CR0H4CK3R
     
The following codes crash new 3ds 11.8
[PP Not Decrease v1.2]
5808FA28 E1A04000
50669020 00000000
00669020 00000010
D0000000 00000000
D0000000 00000000
60669020 00000000
D9000000 00669020
D4000000 FFFFFFFF
D6000000 00669020
D0000000 00000000
D3000000 00000000
50669020 00000001
005BBC14 E1A04000
005BBC18 E92D4007
005BBC1C E59F0018
005BBC20 E2801018
005BBC24 E4902004
005BBC28 E1560002
005BBC2C 03A04000
005BBC30 E1510000
005BBC34 1AFFFFFA
005BBC38 E8BD8007
005BBC3C 300073EC
0808FA28 EBF95879
D0000000 00000000

[HP Not Decrease v1.2]
58099DC4 E1D021B0
5066901C 00000000
0066901C 00000010
D0000000 00000000
D0000000 00000000
6066901C 00000000
D9000000 0066901C
D4000000 FFFFFFFF
D6000000 0066901C
D0000000 00000000
D3000000 00000000
5066901C 00000001
005BBBD4 E1D021B0
005BBBD8 E92D407C
005BBBDC E59F2024
005BBBE0 E59F3024
005BBBE4 E2834018
005BBBE8 E4925004
005BBBEC E4936004
005BBBF0 E1500005
005BBBF4 11500006
005BBBF8 03A01000
005BBBFC E1530004
005BBC00 1AFFFFF8
005BBC04 E8BD807C
005BBC08 30000404
005BBC0C 300073EC
08099DC4 EBF92F82
D0000000 00000000

[Always critical hit v1.2]
58087FF0 E59D0000
50669018 00000000
00669018 00000010
D0000000 00000000
D0000000 00000000
60669018 00000000
D9000000 00669018
D4000000 FFFFFFFF
D6000000 00669018
D0000000 00000000
D3000000 00000000
50669018 00000001
005BBB90 E59D0000
005BBB94 E92D401E
005BBB98 E59A1008
005BBB9C E2813004
005BBBA0 E281401C
005BBBA4 E4932004
005BBBA8 E1500002
005BBBAC 03A01001
005BBBB0 058D1018
005BBBB4 E1530004
005BBBB8 1AFFFFF9
005BBBBC E8BD801E
08087FF0 EBF976E6
D0000000 00000000

[1Hit Kill v1.2]
58021928 E5960004
50669028 00000000
00669028 00000010
D0000000 00000000
D0000000 00000000
60669028 00000000
D9000000 00669028
D4000000 FFFFFFFF
D6000000 00669028
D0000000 00000000
D3000000 00000000
50669028 00000001
005BBAC0 E5960004
005BBAC4 E92D401C
005BBAC8 E59F302C
005BBACC E2834018
005BBAD0 E4932004
005BBAD4 E1580002
005BBAD8 059D1024
005BBADC 03A05000
005BBAE0 01C151B0
005BBAE4 02411A07
005BBAE8 01C152B8
005BBAEC 03A05801
005BBAF0 E1530004
005BBAF4 1AFFFFF5
005BBAF8 E8BD801C
005BBAFC 300073EC
08021928 EBFB1064
D0000000 00000000

[Can throw Pokeball at Trial v1.2]
580BC8AC E1A01004
50669014 00000000
00669014 00000010
D0000000 00000000
D0000000 00000000
60669014 00000000
D9000000 00669014
D4000000 FFFFFFFF
D6000000 00669014
D0000000 00000000
D3000000 00000000
50669014 00000001
08077D10 E3A00001
080BC8AC E3A01000
D0000000 00000000

[Hold SELECT to view IVs & START to view EVs on Status Screen v1.2]
004AF638 E92D4070
004AF9A4 E92D4070
004AF768 E92D4070
004AF7B4 E92D4070
004AF9F0 E92D4070
004AFA3C E92D4070
004AF71C E92D4070
DD000000 00000004
5800A21C EBFFFC13
004AF638 EAFFFCE1
004AF9A4 EAFFFC06
004AF768 EAFFFCF9
004AF7B4 EAFFFCF3
004AF9F0 EAFFFCF8
004AFA3C EAFFFCF2
004AF71C EAFFFCFF
D2000000 00000000
DD000000 00000008
5800A21C EBFFFC13
004AF638 EAFFFC82
004AF9A4 EAFFFBA7
004AF768 EAFFFCD6
004AF7B4 EAFFFCCE
004AF9F0 EAFFFCC6
004AFA3C EAFFFCBE
004AF71C EAFFFCDE
D2000000 00000000

[Can use mega evolution multiple times in a fight v1.2]
580A6150 E12FFF32
50669024 00000000
00669024 00000010
D0000000 00000000
D0000000 00000000
60669024 00000000
D9000000 00669024
D4000000 FFFFFFFF
D6000000 00669024
D0000000 00000000
D3000000 00000000
50669024 00000001
080A6150 E3A00000
D0000000 00000000

[100%Catch v1.2]
5803651C 0A000004
50669004 00000000
00669004 00000010
D0000000 00000000
D0000000 00000000
60669004 00000000
D9000000 00669004
D4000000 FFFFFFFF
D6000000 00669004
D0000000 00000000
D3000000 00000000
50669004 00000001
0803651C EA000004
D0000000 00000000

[No Encounter, Hold START Instant Encounter v1.1 & v1.2]
5807E5B8 E3A00064
0807E5B0 E3A09000
DD000000 00000008
0807E5B0 E3A09064
D0000000 00000000
D0000000 00000000

[No Forced Trainer Battles v1.1 & v1.2]
58032034 EB00F53B
08032034 E3A00001
D0000000 00000000

[Camera zoom out(SELECT+L)Enable, (SELECT+R)Disable v1.1 & v1.2]
605BBF80 ED940A1C
005BBF80 ED940A1C
005BBF84 ED9F1A03
005BBF88 EE300A01
005BBF8C ED840A1C
005BBF90 E2840004
005BBF94 E12FFF1E
005BBF98 00000000
D0000000 00000000
5803B920 E2840004
0803B920 EBFAA996
D0000000 00000000
DD000000 00000204
005BBF98 C4BB8000
D0000000 00000000
DD000000 00000104
005BBF98 00000000
D0000000 00000000

[Can use Z-moves multiple times v1.1 & v1.2]
58031E7C E320F000
5066900C 00000000
0066900C 00000010
D0000000 00000000
D0000000 00000000
6066900C 00000000
D9000000 0066900C
D4000000 FFFFFFFF
D6000000 0066900C
D0000000 00000000
D3000000 00000000
5066900C 00000001
08031E74 E3A00000
08031E78 E5C30005
08031E7C E1500000
D0000000 00000000

**Comment by JourneyOver** [comment] 2018-10-06 19:24
Haven't seen any other reports of this along with testing and no crashes for any friends with testing those codes, i am going to say this is probably just an issue on your side..

Closing this as i can't reproduce

**Closed as completed by JourneyOver** 2018-10-06 19:24 UTC
